spring.application.name=room-service
<<<<<<< HEAD
server.port=8086

=======
server.port=8080
server.servlet.context-path=/room-service
>>>>>>> 20c111787ba3dac6ab159bd1b621208c8b726204
#mysel
# Database connection
spring.datasource.url=jdbc:mysql://localhost:3306/room_db
spring.datasource.username=root
spring.datasource.password=
